Gallery
Simperfy/CS-EXPO-2022 pull request #23
Opened 2022-01-24 15:15 UTC by knhrvs

Working Gallery + Responsive

pacheck

2022-01-24 15:22 UTC, DauntlessDev reviewed
Good Job! It's great that it works, but before approving this one, try to add a background color in the div that contains the three pictures and the title. Also, try to follow the design of the alternating position of the picture by using margins or padding. Add another div that contains one picture, then inside that div, you can add a margin on either top or bottom of the picture. That's how I thought of how it could be done, but there are many ways to implement it, so it depends on what you like and what works. :D

![image](https://user-images.githubusercontent.com/45929622/150810779-15917f2a-09ac-4724-a646-4ed4df2da365.png)

2022-01-24 15:46 UTC, Simperfy requested changes
Awesome! Just need minor changes. 💯

2022-01-24 15:46 UTC, Simperfy commented on src/components/CarouselGallery.tsx
> +export default function Carousel({images, img}) {
Variable names are confusing, maybe we can rename it to something like this:
```diff
- export default function Carousel({images, img}) {
+export default function Carousel({imagesMobile, imagesDesktop}) {
```

2022-01-24 15:46 UTC, Simperfy commented on src/components/CarouselGallery.tsx
> +        const isBigScreen = useMediaQuery({ query: '(min-width: 768px)' })
This could be done in plain css or in tailwind.

2022-01-24 15:46 UTC, Simperfy commented on src/components/CarouselGallery.tsx
> +                ))) :
i didn't test this, but using tailwind something like this should do.
This will hide the div on mobile and is only visible on medium size screen.
```jsx
<div class="hidden md:block">
  {img.map((img) => (
      <div key={img}>
  
              <div class="inline-grid grid-cols-3 gap-4">
                      <img className="carousel-img brightness-75" src={img.backgroundImageF} />
                      <img className="carousel-img brightness-75" src={img.backgroundImageS} />
                      <img className="carousel-img brightness-75" src={img.backgroundImageT} />
              </div>
          </div>
  
  ))}
</div>
```

2022-01-24 15:46 UTC, Simperfy commented on src/components/CarouselGallery.tsx
> +                ))) }
This should display the element on screen and hide on medium screen. *Again, I did not test this*.
```jsx
<div class="block md:hidden">
{images.map((image) => (
    <div key={image}>
        <img className="carousel-img brightness-75" src={image.backgroundImage} />
    </div>
))}
</div>
```

2022-01-24 15:46 UTC, Simperfy commented on src/components/CarouselGallery.tsx
> +                                    <img className="carousel-img brightness-75" src={img.backgroundImageT} />
Poor naming of variable, what does `F` mean in `backgroundImageF`? `S` in `backgroundImageS`? `T` in `backgroundImageT`?

2022-01-24 15:46 UTC, Simperfy commented on src/pages/gallery.astro
> +];
I think it's better if this is structured like this:
```js
const images = {
  desktop: [
    {
        backgroundImageF: 'https://via.placeholder.com/300x300/0000FFC',
	backgroundImageS: 'https://via.placeholder.com/300x300/0000FFC',
	backgroundImageT: 'https://via.placeholder.com/300x300/0000FFC',  
    },
    // ...
  ],
  mobile: [
    {
      backgroundImage: 'https://via.placeholder.com/300x300/0000FFC',
    },
    // ...
  ]
};
```

2022-01-25 18:16 UTC, knhrvs commented on src/components/CarouselGallery.tsx
> +export default function Carousel({images, img}) {
Done

2022-01-25 18:19 UTC, knhrvs commented on src/components/CarouselGallery.tsx
> +                                    <img className="carousel-img brightness-75" src={img.backgroundImageT} />
Changed to:

```
backgroundImageF to backgroundImageFirst
backgroundImageS to backgroundImageSecond
backgroundImageT to backgroundImageThird
```

2022-01-25 18:19 UTC, knhrvs commented on src/pages/gallery.astro
> +];
done na din

2022-01-26 06:44 UTC, DauntlessDev reviewed
Great job, it looks the same with the prototype. But last request :D, i know its slightly different from the prototype, but decrease the gap between photos and add more margin on the sides. 
Just for the improvement of the UI. Thankyou!! 

![image](https://user-images.githubusercontent.com/45929622/151130477-792c869c-cccb-4913-afe5-e22390da1f86.png)

2022-01-26 06:54 UTC, Simperfy reviewed
Looks good to me. 💯

2022-01-26 11:54 UTC, DauntlessDev approved these changes
Great Work Oresca!

2022-01-26 12:12 UTC, Simperfy approved these changes

2022-01-26 12:20 UTC, merged