**Gallery with Images**
Simperfy/CS-EXPO-2022 pull request #28
Opened 2022-02-07 06:26 UTC by knhrvs

***crop lang yung images okay lang ba yon??

2022-02-07 06:33 UTC, Simperfy requested changes

2022-02-07 06:33 UTC, Simperfy commented on src/pages/gallery.astro
> +      backgroundImageFirst: 'images/gallery/csconk217/During4.jpg',
Images not found on deployment
![image](https://user-images.githubusercontent.com/28738855/152736203-69b6e186-4c40-460d-a998-e234c9820bc5.png)

Solution: add prefix to all assets path with `/`

```diff
-backgroundImageFirst: 'images/gallery/csconk217/During4.jpg',
+backgroundImageFirst: '/images/gallery/csconk217/During4.jpg',
```

2022-02-07 06:49 UTC, knhrvs commented on src/pages/gallery.astro
> +      backgroundImageFirst: 'images/gallery/csconk217/During4.jpg',
okay na

2022-02-07 06:49 UTC, knhrvs commented
**may na encounter pala akong problem sa dark mode

2022-02-07 06:51 UTC, Simperfy commented
> **may na encounter pala akong problem sa dark mode

Huwag mo na pansinin iyan, ireremove na natin dark mode.

2022-02-09 17:22 UTC, DauntlessDev requested changes
I asked for feedback from the co-head and head and they said that the picture's proportion gets distorted in some sizes of screen, it is better to make it not scale and just center crop the picture if the picture size doesn't match the screen size. Thanks ! 🤩

2022-02-11 05:46 UTC, Simperfy approved these changes

2022-02-12 15:05 UTC, knhrvs commented
> I asked for feedback from the co-head and head and they said that the picture's proportion gets distorted in some sizes of screen, it is better to make it not scale and just center crop the picture if the picture size doesn't match the screen size. Thanks ! 🤩

i just updated na yung mobile view ng galley and okay na sya di na distorted yung images, may nakalimutan lang pala ako alisin. Then another concern ko pala is diba may images na di sakto kaya naglagay ako ng border sa taas and baba nya okay lang ba yon?

2022-02-13 09:24 UTC, DauntlessDev approved these changes

2022-02-13 09:24 UTC, merged