Partner Page (only missing one uni-org)
Simperfy/CS-EXPO-2022 pull request #44
Opened 2022-03-16 18:06 UTC by Raitou

As I can't find info about the partner_4 in the uni org it won't be there. In the meantime until information about partner_4 has been found this will be the current final partner page.

2022-03-16 23:35 UTC, Simperfy commented
Images are not found on deployment, please prefix all image path with "/"
![image](https://user-images.githubusercontent.com/28738855/158708487-44b0e43f-2bc7-483e-b989-505045ae4539.png)

2022-03-16 23:47 UTC, Simperfy requested changes

2022-03-16 23:47 UTC, Simperfy commented on src/components/Dictionaries/PartnerStrings.js
> +    "Partner_1_Image" : "images/partners/gigabyte/partner_1.jpg",
```suggestion
    "Partner_1_Image" : "/images/partners/gigabyte/partner_1.jpg",
```

2022-03-16 23:47 UTC, Simperfy commented on src/components/Dictionaries/PartnerStrings.js
> +    "Partner_2_Image" : "images/partners/gigabyte/partner_2.jpg",
```suggestion
    "Partner_2_Image" : "/images/partners/gigabyte/partner_2.jpg",
```

2022-03-16 23:47 UTC, Simperfy commented on src/components/Dictionaries/PartnerStrings.js
> +    "Partner_3_Image" : "images/partners/gigabyte/partner_3.jpg",
```suggestion
    "Partner_3_Image" : "/images/partners/gigabyte/partner_3.jpg",
```

2022-03-16 23:47 UTC, Simperfy commented on src/components/Dictionaries/PartnerStrings.js
> +    "Partner_4_Image" : "images/partners/gigabyte/partner_4.jpg",
```suggestion
    "Partner_4_Image" : "/images/partners/gigabyte/partner_4.jpg",
```

2022-03-16 23:47 UTC, Simperfy commented on src/components/Dictionaries/PartnerStrings.js
> +    "Partner_5_Image" : "images/partners/gigabyte/partner_5.jpg",
```suggestion
    "Partner_5_Image" : "/images/partners/gigabyte/partner_5.jpg",
```

2022-03-16 23:47 UTC, Simperfy commented on src/components/Dictionaries/PartnerStrings.js
> +    "Partner_6_Image" : "images/partners/gigabyte/partner_6.jpg",
```suggestion
    "Partner_6_Image" : "/images/partners/gigabyte/partner_6.jpg",
```

2022-03-16 23:47 UTC, Simperfy commented on src/components/Dictionaries/PartnerStrings.js
> +    "Partner_7_Image" : "images/partners/gigabyte/partner_7.jpg",
```suggestion
    "Partner_7_Image" : "/images/partners/gigabyte/partner_7.jpg",
```

2022-03-16 23:47 UTC, Simperfy commented on src/components/Dictionaries/PartnerStrings.js
> +    "Partner_8_Image" : "images/partners/gigabyte/partner_8.jpg",
```suggestion
    "Partner_8_Image" : "/images/partners/gigabyte/partner_8.jpg",
```

2022-03-16 23:47 UTC, Simperfy commented on src/components/Dictionaries/PartnerStrings.js
> +    "Partner_1_Image" : "images/partners/uni/partner_1.jpg",
```suggestion
    "Partner_1_Image" : "/images/partners/uni/partner_1.jpg",
```

2022-03-16 23:47 UTC, Simperfy commented on src/components/Dictionaries/PartnerStrings.js
> +    "Partner_2_Image" : "images/partners/uni/partner_2.jpg",
```suggestion
    "Partner_2_Image" : "/images/partners/uni/partner_2.jpg",
```

2022-03-16 23:47 UTC, Simperfy commented on src/components/Dictionaries/PartnerStrings.js
> +    "Partner_3_Image" : "images/partners/uni/partner_3.jpg",
```suggestion
    "Partner_3_Image" : "/images/partners/uni/partner_3.jpg",
```

2022-03-17 00:10 UTC, Simperfy commented
I suggest adding spacing to the top of image and lessen the gap with the social links.
![image](https://user-images.githubusercontent.com/28738855/158711287-7f72aa14-217f-4a54-9098-af908509268c.png)

2022-03-17 00:23 UTC, DauntlessDev commented
Great Suggestions @Simperfy

2022-03-17 05:38 UTC, Raitou commented
Please check latest pull regarding this for the update thanks!

2022-03-17 05:38 UTC, closed without merging